/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    CurrencyPicker: typeof import('./src/components/inputs/CurrencyPicker.vue')['default']
    DateRangePicker: typeof import('./src/components/inputs/DateRangePicker.vue')['default']
    IncomeChart: typeof import('./src/components/outputs/IncomeChart.vue')['default']
    SummaryTable: typeof import('./src/components/outputs/SummaryTable.vue')['default']
    ValidatorAdder: typeof import('./src/components/inputs/ValidatorAdder.vue')['default']
  }
}
