"""v2 Rocket Pool tables

Revision ID: 072ff1540642
Revises: e9d91d6ad279
Create Date: 2024-01-21 14:09:29.012460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072ff1540642'
down_revision = 'e9d91d6ad279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rocket_pool_node',
    sa.Column('node_address', sa.String(length=42), nullable=False),
    sa.Column('fee_distributor', sa.String(length=42), nullable=False),
    sa.PrimaryKeyConstraint('node_address'),
    sa.UniqueConstraint('node_address')
    )
    op.create_table('rocket_pool_reward_period',
    sa.Column('reward_period_index', sa.Integer(), nullable=False),
    sa.Column('reward_period_end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('reward_period_index')
    )
    op.create_table('rocket_pool_minipool',
    sa.Column('minipool_address', sa.String(length=42), nullable=False),
    sa.Column('validator_pubkey', sa.String(length=98), nullable=False),
    sa.Column('initial_bond_value', sa.Numeric(precision=20), nullable=False),
    sa.Column('initial_fee_value', sa.Numeric(precision=19), nullable=False),
    sa.Column('node_address', sa.String(length=42), nullable=False),
    sa.ForeignKeyConstraint(['node_address'], ['rocket_pool_node.node_address'], ),
    sa.PrimaryKeyConstraint('minipool_address')
    )
    op.create_table('rocket_pool_reward',
    sa.Column('node_address', sa.String(length=42), nullable=False),
    sa.Column('reward_collateral_rpl', sa.Numeric(precision=27), nullable=False),
    sa.Column('reward_smoothing_pool_wei', sa.Numeric(precision=27), nullable=False),
    sa.Column('reward_period_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_period_index'], ['rocket_pool_reward_period.reward_period_index'], ),
    sa.PrimaryKeyConstraint('node_address', 'reward_period_index')
    )
    op.create_table('rocket_pool_bond_reduction',
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('new_bond_amount', sa.Numeric(precision=27), nullable=False),
    sa.Column('new_fee', sa.Numeric(precision=19), nullable=False),
    sa.Column('minipool_address', sa.String(length=42), nullable=False),
    sa.ForeignKeyConstraint(['minipool_address'], ['rocket_pool_minipool.minipool_address'], ),
    sa.PrimaryKeyConstraint('new_bond_amount', 'minipool_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rocket_pool_bond_reduction')
    op.drop_table('rocket_pool_reward')
    op.drop_table('rocket_pool_minipool')
    op.drop_table('rocket_pool_reward_period')
    op.drop_table('rocket_pool_node')
    # ### end Alembic commands ###
