"""Add table for Rocketpool minipools

Revision ID: 08eb0b12b716
Revises: 4ae53a12b550
Create Date: 2023-10-27 16:17:46.278925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08eb0b12b716'
down_revision = '4ae53a12b550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rocketpool_minipool',
    sa.Column('minipool_index', sa.Integer(), nullable=False),
    sa.Column('validator_index', sa.Integer(), nullable=False),
    sa.Column('node_address', sa.String(length=42), nullable=False),
    sa.Column('node_deposit_balance', sa.String(length=20), nullable=False),
    sa.Column('fee', sa.Numeric(precision=19), nullable=False),
    sa.Column('bond_reduced_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('bond_pre_reduction_value_wei', sa.Numeric(precision=27), nullable=True),
    sa.PrimaryKeyConstraint('minipool_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rocketpool_minipool')
    # ### end Alembic commands ###
