"""Add index for validator_index in withdrawal

Revision ID: 09714230640a
Revises: 991c5c3c836a
Create Date: 2023-08-28 10:58:51.459290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09714230640a'
down_revision = '991c5c3c836a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_withdrawal_validator_index'), 'withdrawal', ['validator_index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_validator_index'), table_name='withdrawal')
    # ### end Alembic commands ###
