"""Add table for block rewards

Revision ID: 433dd90de0b1
Revises: f7053ac981c7
Create Date: 2022-11-04 19:13:39.070159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433dd90de0b1'
down_revision = 'f7053ac981c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_reward',
    sa.Column('slot', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('proposer_index', sa.Integer(), nullable=True),
    sa.Column('fee_recipient', sa.String(length=42), nullable=True),
    sa.Column('proposer_reward', sa.Numeric(precision=27, scale=0), nullable=True),
    sa.Column('mev', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('slot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_reward')
    # ### end Alembic commands ###
