"""Add tables for Rocketpool

Revision ID: 4ae53a12b550
Revises: 06aab3e116c5
Create Date: 2023-10-27 13:37:49.558736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae53a12b550'
down_revision = '06aab3e116c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rocketpool_reward',
    sa.Column('node_address', sa.String(length=42), nullable=False),
    sa.Column('reward_period_index', sa.Integer(), nullable=False),
    sa.Column('reward_collateral_rpl', sa.Numeric(precision=27), nullable=False),
    sa.Column('reward_smoothing_pool_wei', sa.Numeric(precision=27), nullable=False),
    sa.PrimaryKeyConstraint('node_address', 'reward_period_index')
    )
    op.create_table('rocketpool_reward_period',
    sa.Column('reward_period_index', sa.Integer(), nullable=False),
    sa.Column('reward_period_end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('reward_period_index')
    )
    op.alter_column('block_reward', 'reward_processed_ok',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_reward', 'reward_processed_ok',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('rocketpool_reward_period')
    op.drop_table('rocketpool_reward')
    # ### end Alembic commands ###
