"""store block number

Revision ID: bc3c15a3efcd
Revises: 0a98fcf0416d
Create Date: 2024-01-25 09:37:59.484215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3c15a3efcd'
down_revision = '0a98fcf0416d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_reward', sa.Column('block_number', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_reward', 'block_number')
    # ### end Alembic commands ###
