"""Add block_extra_data column to block rewards table

Revision ID: c74d63d8ee4c
Revises: 433dd90de0b1
Create Date: 2022-11-05 13:46:52.905348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74d63d8ee4c'
down_revision = '433dd90de0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_reward', sa.Column('block_extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_reward', 'block_extra_data')
    # ### end Alembic commands ###
