"""Add price data

Revision ID: d0f0663435bf
Revises: bc3c15a3efcd
Create Date: 2024-10-31 11:48:32.880513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f0663435bf'
down_revision = 'bc3c15a3efcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('token', 'currency', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    # ### end Alembic commands ###
