"""Add table for withdrawal data

Revision ID: e2344e393641
Revises: 328c9940a8e8
Create Date: 2023-04-17 12:58:39.381724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2344e393641'
down_revision = '328c9940a8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal',
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('validator_index', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=27), nullable=True),
    sa.PrimaryKeyConstraint('slot', 'validator_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal')
    # ### end Alembic commands ###
