{
 "title": "ETH2.tax Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "path", "query": { "query": "label_values(path)\t" } }
  ]
 },
 "panels": [
  { "title": "Rewards requests stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "By date range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rewards_request_total[$__range])) by (calendar_year)",
     "legendFormat": "{{ calendar_year }}"
    }
   ]
  },
  {
   "title": "By timezone",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(rewards_request_total[$__range])) by (timezone)",
     "legendFormat": "{{ timezone }}"
    }
   ]
  },
  {
   "title": "By currency",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(rewards_request_total[$__range])) by (currency)",
     "legendFormat": "{{ currency }}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "API endpoints usage [last 24h]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(starlette_requests_total{job=\"api\", path!~\"/(metrics|openapi.json|docs)\"}[24h])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "API docs visits [last 24h]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(starlette_requests_total{job=\"api\", path=\"/api/v1/docs\"}[24h])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Validators per ETH1 address",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(validators_per_eth1_address_bucket[5m])) by (le) > 0",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Validators per /rewards request [5m]",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(validators_per_rewards_request_bucket[5m])) by (le) > 0",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Services running",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Services running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Available disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_avail_bytes{mountpoint=\"/etc/hostname\"}) / node_filesystem_size_bytes{mountpoint=\"/etc/hostname\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Caddy requests total [1h]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(caddy_http_requests_total[1h])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Caddy requests duration [5m]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket[5m])) by (le) > 0",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Starlette requests total - API [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_total{job=\"api\", path!=\"/metrics\"}[1h])",
     "legendFormat": "{{path}}->{{status_code}}"
    }
   ]
  },
  {
   "title": "Starlette requests total - frontend [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_total{job=\"frontend\", path!=\"/metrics\"}[1h])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Starlette requests OK status codes [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starlette_requests_total{path!~\"/metrics\", status_code=~\"200|304\"}[1h])) by (status_code)",
     "legendFormat": "{{status_code}} {{path}}"
    }
   ]
  },
  {
   "title": "Starlette requests NOK status codes [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starlette_requests_total{path!~\"/metrics\", status_code!~\"200|304\"}[1h])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Starlette requests 5xx status codes [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(starlette_requests_total{path!~\"/metrics\", status_code=~\"5\\\\d\\\\d\"}[1h])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Path specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Request duration [5m]",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(increase(starlette_request_duration_seconds_bucket{path=\"$path\", status_code=\"200\"}[5m])) by (le) > 0",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Total requests [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_total{path=\"$path\"}[1h])",
     "legendFormat": "{{path}} - {{status_code}}"
    }
   ]
  },
  { "title": "Data providers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Requests made to beaconcha.in [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beaconchain_request_count_total[1h])",
     "legendFormat": "by {{ job }}"
    }
   ]
  },
  {
   "title": "Requests made to CoinGecko [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(coin_gecko_request_count_total[1h])",
     "legendFormat": "{{ path }} by {{ job }}"
    }
   ]
  },
  {
   "title": "Requests made to beacon node [1h]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_node_request_count_total[1h])",
     "legendFormat": "{{path}} (by {{job}})"
    }
   ]
  },
  {
   "title": "DB request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(db_requests_seconds_bucket[5m])) by (le) > 0",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Balance indexer - slots with missing balances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slots_with_missing_balances" }
   ]
  },
  {
   "title": "Connections by state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"eth2tax\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transaction rate [5m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit[5m])))+sum((rate(pg_stat_database_xact_rollback[5m])))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "PostgreSQL version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_server_version_num" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(process_start_time_seconds{job=\"pg_exporter\"})"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"eth2tax\"}"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(pg_stat_database_xact_commit)/(sum(pg_stat_database_xact_commit) + sum(pg_stat_database_xact_rollback))"
    }
   ]
  }
 ]
}